# Generated by Django 3.1.3 on 2023-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='course',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.CharField(choices=[('True', 'Correct'), ('False', 'Incorrect')], default='False', max_length=20),
        ),
    ]
